#!/bin/bash

# DisableWifiOnBoot Script
# Run on BT Device Connect
# Check if line written
grep -q "dtoverlay=pi3-disable-wifi" /boot/config.txt
        if [[ $(echo $?) == 1 ]];
        then
                echo "Line not in /boot/config.txt"
                # Write Line
                sudo sed '/#_Disable_Onboard_WIFI/ a dtoverlay=pi3-disable-wifi' -i /boot/config.txt;echo $?
                echo "Writing line to disable WIFI on boot"
        else
                echo "Line exists already, WIFI will be disabled on boot"
        fi
echo "Done Disabling Wifi On Next Boot"

#Disable DHCPCD on next boot in hopes of speeding up boot time
sudo update-rc.d -f dhcpcd remove
